version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: myband-db
    restart: always
    environment:
      POSTGRES_USER: myband_user
      POSTGRES_PASSWORD: myband_pass
      POSTGRES_DB: myband_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
